# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "http://www.your-domain.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Luna Kang # Your name will go here
  description: "Luna Kang's personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h2>LET'S BUILD<br>SOMETHING<BR>TOGETHER</h2>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: lkang-pdx
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/lunakang
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  tumblr:
  twitter: TheLunaKang
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-87672791-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Montserrat:400,700|Droid+Serif:400,700,400italic,700italic|Kaushan+Script"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
